"""Integration test for email sending functionality.

This test requires a valid SENDGRID_API_KEY (MailerSend) in the .env file.
It is skipped by default in pytest runs.

Note: Despite the env var name, this uses MailerSend API (for backward compatibility).

To run this test specifically:
    pytest tests/integration/test_email_send.py --run-email

Or with verbose output:
    pytest tests/integration/test_email_send.py --run-email -v
"""

import os
from datetime import datetime

import pytest
from dotenv import load_dotenv

from notch_chatbot.tools import create_and_send_offer

# Load .env file before the test
load_dotenv()


@pytest.mark.integration
@pytest.mark.email
@pytest.mark.asyncio
async def test_send_sample_email():
    """Test sending a sample proposal email via MailerSend.

    This test will send a real email to the configured test recipient.
    Make sure SENDGRID_API_KEY is set in your .env file (contains MailerSend API key).

    The email will be sent directly to the test recipient (no BCC).
    """
    # Check if API key is configured
    api_key = os.getenv("SENDGRID_API_KEY")
    if not api_key:
        pytest.fail(
            "SENDGRID_API_KEY not found in environment. "
            "Please add it to your .env file."
        )

    # Test email data
    test_client_name = "Test Client"
    test_client_email = "darko.spoljaric@wearenotch.com"  # Use different email from BCC
    test_project_description = (
        "Test project for integration testing the email sending functionality. "
        "This is a sample proposal generated by automated testing to verify "
        "that the email sending system works correctly."
    )
    test_services = "- Custom Software Development\n- AI Integration\n- MVP Development"
    test_scope = "medium"

    # Send the test email
    print(f"\n{'=' * 60}")
    print(f"Sending test email to: {test_client_email}")
    print(f"API Key prefix: {api_key[:10]}...")
    print(f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"{'=' * 60}\n")

    result = await create_and_send_offer(
        client_name=test_client_name,
        client_email=test_client_email,
        project_description=test_project_description,
        services_list=test_services,
        project_scope=test_scope,
    )

    print(f"\nResult: {result}")
    print(f"{'=' * 60}\n")

    # Check for authentication errors
    if (
        "401" in result
        or "403" in result
        or "invalid" in result.lower()
        or "expired" in result.lower()
    ):
        pytest.fail(
            f"MailerSend API authentication failed. This usually means:\n"
            f"1. The API key is invalid or expired\n"
            f"2. The API key doesn't have the correct permissions (needs 'Email' access)\n"
            f"3. The sender email (proposals@wearenotch.com) is not verified in MailerSend\n\n"
            f"Please:\n"
            f"- Generate a new API key from MailerSend dashboard: https://app.mailersend.com/api-tokens\n"
            f"- Ensure the API token has 'Email' access enabled\n"
            f"- Verify the sender domain: https://app.mailersend.com/domains\n\n"
            f"Error: {result}"
        )

    # Check for domain verification errors
    if "422" in result and (
        "domain must be verified" in result.lower() or "ms42207" in result.lower()
    ):
        pytest.fail(
            f"MailerSend domain verification required. The error indicates:\n"
            f"The sender domain 'wearenotch.com' must be verified in your MailerSend account.\n\n"
            f"To fix this:\n"
            f"1. Go to https://app.mailersend.com/domains\n"
            f"2. Add and verify the domain 'wearenotch.com'\n"
            f"3. Add the required DNS records (TXT, CNAME, MX)\n"
            f"4. Wait for DNS propagation (can take up to 24 hours)\n"
            f"5. Click 'Verify domain' in MailerSend dashboard\n\n"
            f"Alternatively, you can use a verified domain that's already in your MailerSend account.\n\n"
            f"Error: {result}"
        )

    # Check for BCC limit errors
    if "422" in result and "bcc recipient limit" in result.lower():
        pytest.skip(
            f"MailerSend BCC limit exceeded. Free tier has restrictions on BCC recipients.\n"
            f"This is a known limitation. The code works but needs a paid plan for BCC.\n\n"
            f"Error: {result}"
        )

    # Verify the result indicates success
    assert "✓" in result or "sent successfully" in result.lower(), (
        f"Email sending failed. Result: {result}"
    )

    print("✓ Test email sent successfully!")
    print("Check your inbox (and spam folder) for the test proposal.")


@pytest.mark.integration
@pytest.mark.email
@pytest.mark.asyncio
async def test_send_email_missing_api_key(monkeypatch):
    """Test that proper error is returned when API key is missing.

    This test doesn't actually send an email - it just verifies error handling.
    """
    # Remove the API key from environment
    monkeypatch.delenv("SENDGRID_API_KEY", raising=False)

    result = await create_and_send_offer(
        client_name="Test Client",
        client_email="test@example.com",
        project_description="Test project",
        services_list="Test services",
        project_scope="small",
    )

    # Should return an error message about missing API key
    assert "SENDGRID_API_KEY not configured" in result
